name: Generate APK and AAB (Upload to GitHub Action)

env:
  main_project_module: app

on:
  push:
    branches:
      - 'release/**'   # Matches any branch under 'release/'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Set Current Date As Env Variable
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # Set Repository Name As Env Variable
      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      # Run Tests
      - name: Run gradle tests
        run: ./gradlew test --warning-mode all

      # Build APK Debug
      - name: Build APK debug
        run: ./gradlew assembleDebug --warning-mode all

      # Build APK Release
      - name: Build APK release
        run: ./gradlew assembleRelease --warning-mode all

      # Build AAB Release
      - name: Build AAB release
        run: ./gradlew ${{ env.main_project_module }}:bundleRelease --warning-mode all

      # Verify APK and AAB Files
      - name: List APK and AAB Output Files
        run: ls -R ${{ env.main_project_module }}/build/outputs/

      # Upload APK Debug
      - name: Upload APK Debug
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.date_today }} - ${{ env.repository_name }} - APK debug
          path: ${{ env.main_project_module }}/build/outputs/apk/debug/*.apk

      # Upload APK Release
      - name: Upload APK Release
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.date_today }} - ${{ env.repository_name }} - APK release
          path: ${{ env.main_project_module }}/build/outputs/apk/release/*.apk

      # Upload AAB Release
      - name: Upload AAB Release
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.date_today }} - ${{ env.repository_name }} - AAB release
          path: ${{ env.main_project_module }}/build/outputs/bundle/release/*.aab
