name: Input Validation Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK for the Android environment
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # Grant execute permissions for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      # Build the project
      - name: Build Project
        run: ./gradlew assembleDebug

      # Run Unit Tests
      - name: Run Unit Tests
        run: ./gradlew :app:testDebugUnitTest