name: SharedPreferences Instrumentation Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          target: default
          arch: x86

      - name: Start emulator
        run: |
          sdkmanager "system-images;android-30;google_apis;x86"
          avdmanager create avd -n test -k "system-images;android-30;google_apis;x86" -d "pixel" --force
          emulator -avd test -no-snapshot -no-window -noaudio &

      - name: Wait for emulator to boot
        run: |
          adb wait-for-device
          adb shell 'while [[ "$(getprop sys.boot_completed)" != "1" ]]; do sleep 1; done'

      - name: Run instrumentation tests
        run: ./gradlew connectedAndroidTest

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: app/build/reports/androidTests/connected/
