name: Android Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          target: default
          arch: x86
          profile: default
          emulator-options: "-no-boot-anim -no-snapshot -no-window"

      - name: Start emulator
        run: |
          adb devices
          adb shell input keyevent 82 &

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build and run tests
        run: ./gradlew testDebug
